config/routes.rb
Depot::Application.routes.draw do
 mount WeixinRailsMiddleware::Engine, at: "/"
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resource :weixin

  resources :categories do
    member do
      get :products
    end
  end
 resources :users do
    member do
      get :orders
    end
  end
  resources :orders do
    member do
      get :line_items
    end
  end
  get '/categories/:category_id/products/:id', to: 'store#product_info'

  resources :line_items

  resources :carts
  
  mount ChinaCity::Engine => '/china_city'
  
  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as:'store'

end
 

app/models/user.rb
class User < ActiveRecord::Base
  # It will auto generate weixin token and secret
  include WeixinRailsMiddleware::AutoGenerateWeixinTokenSecretKey
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  has_many :orders, dependent: :destroy
  private
    def ensure_an_admin_remains
    	if User.count.zero?
    		raise "Can't delete last user"
    	end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize
  skip_before_filter :verify_authenticity_token
  before_action :set_user, only: [:orders,:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  
  def orders
    @orders = @user.orders
  end
  
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.hrml.erb
      format.json {render json: @users}
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    params.permit!
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    params.permit!
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User #{@user.name} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exeption => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


    # Use callbacks to share common setup or constraints between actions.
    def set_user
      params.permit!
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id,:name, :password_digest)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class = "depot_form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
<legend>Enter User Details</legend>

  <div class="field">
    <%= f.label :name, 'Name'%><br>
    <%= f.text_field :name, size: 40%>
  </div>

  <div class="field">
    <%= f.label :password, 'Password' %><br>
    <%= f.password_field :password, size: 40 %>
  </div>

   <div class="field">
    <%= f.label :password_confirmation, 'Confirm' %><br>
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p id="notice"><%= notice %></p>

<% end %>
<table>
 <thead>
    <tr>
      <th>Name</th>
      <th>Weixin Server Url</th>
      <th>Weixin Token</th>
    </tr>
  </thead>

  <tbody>
     <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= weixin_engine.weixin_server_url(user.weixin_secret_key) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/orders.html.erb
<% @orders.each do |order| %>
<div id = "f">

<p>
  <strong>名字:</strong>
  <%= order.name %>
  
  <strong>地址:</strong>
  <%= order.address %>

  <strong>联系方式:</strong>
  <%= order.phonenumber %>

  <strong>送货日期:</strong>
  <%= order.date %>

  <strong>送货时间:</strong>
  <%= order.time %>

  <strong>省份:</strong>
  <%= order.province %>

  <strong>城市:</strong>
  <%= order.city %>

  <strong>地区:</strong>
  <%= order.district %>

  <strong>详细地址:</strong>
  <%= order.address %>

  <%= button_to"订单内容",line_items_order_path(order), method: :get%>
</p>
</div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>